# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1 

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    # working_directory: ~/backend_api
    docker:
      - image: circleci/node:5.0.0
    steps:
      - checkout
      - node/install-npm
      - node/test

workflows:
    example-workflow:
      jobs:
        - build

